---

- name: "Ensure directories exist"
  file:
    path: "/etc/syslog-ng/cert.d"
    recurse: yes
    state: directory

- name: "Ensure directories exist"
  file:
    path: "/etc/syslog-ng/ca.d"
    recurse: yes
    state: directory

- name: "Copy client-key for syslog"
  copy:
    src: clientkey.pem
    dest: /etc/syslog-ng/cert.d/clientkey.pem
  become: yes

- name: "Copy client-cert for syslog"
  copy:
    src: clientcert.pem
    dest: /etc/syslog-ng/cert.d/clientcert.pem
  become: yes

- name: "Copy ca-cert for syslog"
  copy:
    src: cacert.pem
    dest: /etc/syslog-ng/ca.d/cacert.pem
  become: yes

